### ISSUE TITLE
Any report of time consuming?

### ISSUE THREAD

**Issue by redreamality** [MingLiiii/Cherry_LLM#13]
I've already changed the tensors into gpu. And i'm pretty sure that I'm using GPU. 
However,  running cherry_seletion/data_analysis.py takes about nearly a month on about a 50k dataset.
Is it normal?

**Comment by MingLiiii** [comment]
Thanks for your interest. 
It's not normal. 
 What GPU do you use? On 1 A6000, it will take only a couple of hours, since it just computes losses and no gradients are required.
