### ISSUE TITLE
'The training of pre-experienced models is discarded for more efficient usage': that means we can only use base model to do cherry analysis and selection?

### ISSUE THREAD

**Issue by Labmem009** [MingLiiii/Cherry_LLM#15]
I noticed your update in README. Did that mean we can only use base model to do cherry analysis and selection? Directly use base model or use pre-experienced model, which performance is better?

**Comment by MingLiiii** [comment]
Thanks for your interest in our work.

For the first question, it would be yes. It is fine to do cherry analysis and selection directly on base Llama2 models.
For the second question, I would say that from the **Research Viewpoint**, using pre-experienced models is more reasonable and performs better. However from the **Real-world Implementation Viewpoint**, directly using the base model is more easy and efficient. It's kind of a tradeoff.
