### ISSUE TITLE
how many epochs to train on cherry data?

### ISSUE THREAD

**Issue by menghonghan** [MingLiiii/Cherry_LLM#19]
I saw from the paper for pre-exprience model, your trained 1 epoch. But after data selection, it's fuzzy in the paper how many epochs you trained on cherry data, it that 3 ?  Looking forward for your quick response.

**Comment by MingLiiii** [comment]
Thank you very much for your interest!
Yes, we trained the cherry model for 3 epochs. 
You can find the detailed parameters in the Implementation Details section of our paper or the Hyperparameters section in our repo~

**Comment by menghonghan** [comment]
Thx
