### ISSUE TITLE
Logic behind IFD score

### ISSUE THREAD

**Issue by mshen2** [MingLiiii/Cherry_LLM#4]
Thanks for your work! I am currently trying to understand the logic behind IFD score and maybe I am misunderstanding something. For equation 4 of the direct answer score, the paper mentions "A higher direct answer score may suggest that the answer is inherently more challenging or intricate for the model to generate". However, isn't it when equation 4 (the probability of the sentence) gives a higher value indicates that the sentence makes more sense so it would be more natural for LM to generate? kindly looking forward to your reply. Thanks!

**Comment by MingLiiii** [comment]
Thanks for asking!
We are really sorry for the confusion. There is a typo in Equation 3 and Equation 4. There should be minus signs on these two equations. 

Apologize again for the mistakes, we will correct this typo and update our manuscript in the next version. 
Let me know if you still have problems~
