### ISSUE TITLE
I plan to apply this method on Llama2, which part of this project needs to be changed to adapt to Llama2?

### ISSUE THREAD

**Issue by Labmem009** [MingLiiii/Cherry_LLM#5]
Very interesting work. I plan to apply this method on Llama2, which part of this project needs to be changed to adapt to Llama2? I noticed that one of your future work is 'Implement our method on llama 2 models.' Do you have any progress? Thanks a lot!

**Comment by MingLiiii** [comment]
Thank you for your interest in our work~
We have done experiments on llama2 on Alpaca data without using the pre-experienced model for simplicity. It works fine, which shows the effectiveness of our approach. We also got the IFD scores of wizardLM data based on llama2 but haven't had time to train them. We will release all these data and model performances soon in the next version. 

I don't think there is much modification that should be made to adapt to llama2. You can directly use it. 
I think there are indeed some things that can be further explored like the use of pre-trained models, or the use of different prompt templates or so. 
So please feel free to explore what you like~
