### ISSUE TITLE
about the paper

### ISSUE THREAD

**Issue by liwenju0** [MingLiiii/Cherry_LLM#7]
<img width="599" alt="image" src="https://github.com/MingLiiii/Cherry_LLM/assets/16049564/74151b22-942a-445f-95b4-2359159b27f3">

I think there's something wrong with this formula. Shouldn't there be a minus sign?

**Comment by MingLiiii** [comment]
Yes, there should be a minus sign. Please refer to #4.
We are sorry for this and we will correct it soon in the next version.
