### ISSUE TITLE
Multi-round conversation data set

### ISSUE THREAD

**Issue by wuQi-666** [MingLiiii/Cherry_LLM#8]
Hello, I observed that the alpaca_data.json dataset we used is in the form of a single round of dialogue. May I ask if you have considered IFD screening for data sets with multiple rounds of dialogue?

**Comment by MingLiiii** [comment]
At least in this project, we are not going to explore the multi-round situation. 

However, we don't think it would be hard to implement the IFD score to multi-round. 
And I think another choice is to check OpenChat? You can see if their method works for you~

**Comment by wuQi-666** [comment]
Can you give me the project address for this method? Thanks

**Comment by MingLiiii** [comment]
https://github.com/imoneoi/openchat
