### ISSUE TITLE
GPT-4/ChatGPT Evaluation Code

### ISSUE THREAD

**Issue by mshen2** [MingLiiii/Cherry_LLM#9]
Hi authors. I am just wondering if it is possible to share the eval_after_wrap.py code. Thanks!

**Comment by MingLiiii** [comment]
I am sorry for the late reply and for the typo!
The "eval_after_wrap.py" is the "evaluation/generation/eval.py" code. You can directly modify the .sh scripts by replacing "eval_after_wrap.py" with "evaluation/generation/eval.py".
